name: frontend
services:
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12200:80"
    environment:
      - GRAPHQL_ENDPOINT=http://scrum_game:12001/graphql
      - GRAPHQL_WS_ENDPOINT=http://scrum_game:12001/graphql-ws
      - WEBHOOK_ENDPOINT=http://scrum_game:12001/webhook
      - GRAPHIQL_ENDPOINT=http://scrum_game:12001/graphiql
      - FIXED_CLIENT_ID=139a95cb-e308-4b4d-862a-dd567843100a
      - AUTH_ENDPOINT=http://gropius-testing-frontend-1:4200/auth/oauth
    networks:
      - scrum-game-network

networks:
  scrum-game-network:
    external: true
