GET http://localhost:8080/sdl


###
GET http://localhost:3000/login/strategyInstance
Accept: application/json

###
POST http://localhost:3000/authenticate/oauth/139a95cb-e308-4b4d-862a-dd567843100a/token/login
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=admin&password=admin&redirect_uri=http://localhost:3000/login/strategyInstance

###
POST http://localhost:3000/authenticate/oauth/139a95cb-e308-4b4d-862a-dd567843100a/token/login
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=paul&password=paul&redirect_uri=http://localhost:3000/login/strategyInstance
###
POST http://localhost:9009/realms/GITS/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=scrum-game-frontend&grant_type=password&username=paul&password=paul
